force-app/main/default/objects/Gifting__c/Gifting__c.object-meta.xml
<CustomObject>
    <label>Gifting</label>
    <nameField>
        <displayFormat>GIFT-{0000}</displayFormat>
        <label>Gifting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Giftings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gifting__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Used to store the house number, street etc.</description>
    <inlineHelpText>Used to store the house number, street etc.</inlineHelpText>
    <label>Address Line 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/Donor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Donor_Contact__c</fullName>
    <label>Donor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Giftings</relationshipLabel>
    <relationshipName>Giftings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <label>Full Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_UT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the status of the gift box in the pipeline.</description>
    <inlineHelpText>Tracks the status of the gift box in the pipeline.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ToBePacked</fullName>
                <default>true</default>
                <label>ToBePacked</label>
            </value>
            <value>
                <fullName>ToBeShipped</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gifting__c/fields/TrackingNumber__c.field-meta.xml
<CustomField>
    <fullName>TrackingNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The tracking number of the gift sent to the user via courier service.</description>
    <inlineHelpText>The tracking number of the gift sent to the user via courier service.</inlineHelpText>
    <label>Tracking Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GiftingController.cls
public class GiftingController {
    public List<Gifting__c> selGfLst { get; set; }
    public String gfIds { get; set; }

    // Constructor that accepts StandardSetController
    public GiftingController(ApexPages.StandardSetController setController) {
        selGfLst = (List<Gifting__c>) setController.getSelected();
        gfIds = '';

        if(selGfLst != null && selGfLst.size() > 0) {
            for(Gifting__c gf : selGfLst) {
                gfIds += gf.Id + ',';
            }
            // Remove the last comma
            gfIds = gfIds.removeEnd(',');
        }
        getGiftingRecords();
    }

    // Method to retrieve full records based on the IDs
    public void getGiftingRecords() {
        if (!String.isEmpty(gfIds)) {
            List<Id> gfIdList = gfIds.split(',');
            selGfLst = [SELECT Id, Name, TrackingNumber__c, Donor_Contact__r.Name, Donor_Contact__r.Phone, Address_Line_1__c, Pincode__c, City__c, State__c, Status__c, Full_Address__c 
                    FROM Gifting__c 
                    WHERE Id IN :gfIdList];
        }
       
    }
}